# hunting_regs.toml

[paths]
input_dir = "data/input"
output_dir = "data/output"

[openai]
model_name = "gpt-4o"
api_key_env = "OPENAI_API_KEY"

[assistant]
name = "RegulationsSummarizer"
vector_store_name = "regs-store"

[species]
valid = [
  "deer",
  "elk",
  "antelope",
  "black-bear",
  "moose",
  "sheep",
  "goat",
  "bison",
  "mountain-lion",
  "wolf",
  "turkey",
  "goose",
  "migratory-bird"
]
